# settings for application


[map]
# whether to save temporary map data (Recommended: true)
saveTempData = true
# Data attribute to be map tile
dataAttribute = "GSI"
# Map tile URL(must be text format)
tileURL = "https://cyberjapandata.gsi.go.jp/xyz/dem/{z}/{x}/{y}.txt"

# specification for each map
# 
# Fomat:
# [[map.spec]]
# name = "<name>"
# northwest = [<latitude>, <longitude>] (northwest corner of the map)
# southeast = [<latitude>, <longitude>] (southeast corner of the map)
# zoom = <zoom level> (Detail level of the map(1 - 14, integer))
# dataAttribute = "<data attribute>" (Optional or inherit from main settings)
# tileURL = "<tile URL>" (Optional or inherit from main settings)
# 
[[map.specs]]
name = "Izu Ōshima"
northwest = [34.808917, 139.331932]
southeast = [34.672182, 139.472122]
zoom = 14
[[map.specs]]
name = "Noshiro Land"
northwest = [40.160750290257795, 139.96924290399346]
southeast = [40.11877471428155, 140.015]
zoom = 14
[[map.specs]]
name = "Noshiro Sea"
northwest = [40.202, 140.006]
southeast = [40.166, 140.08]
zoom = 12